# Generated by Django 6.0.1 on 2026-01-25 19:20

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: L1, L2, M1, D1, etc.', max_length=10, unique=True, verbose_name='code')),
                ('intitule', models.CharField(max_length=100, verbose_name='intitulé')),
                ('ordre', models.PositiveSmallIntegerField(help_text="Ordre d'affichage (1 pour le premier niveau)", unique=True, verbose_name='ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
            ],
            options={
                'verbose_name': 'niveau',
                'verbose_name_plural': 'niveaux',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('SECRETARIAT', 'Secrétariat'), ('ENSEIGNANT', 'Enseignant'), ('RESPONSABLE', 'Responsable Pédagogique')], default='ENSEIGNANT', max_length=15, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=False, help_text="Détermine si l'utilisateur peut se connecter. Les étudiants ne peuvent pas se connecter.", verbose_name='compte actif')),
                ('genre', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], max_length=1, null=True, verbose_name='genre')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide. Ex: +261340000000 ou 0340000000', regex='^\\+?[0-9]{10,15}$')], verbose_name='téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_profils/', verbose_name='photo de profil')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True, verbose_name='lieu de naissance')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='adresse')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('groups', models.ManyToManyField(blank=True, help_text="Les groupes auxquels appartient l'utilisateur.", related_name='application_user_set', related_query_name='application_user', to='auth.group', verbose_name='groupes')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissions spécifiques pour cet utilisateur.', related_name='application_user_set', related_query_name='application_user', to='auth.permission', verbose_name='permissions utilisateur')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code court de la filière (ex: INFO, GESTION)', max_length=10, unique=True, verbose_name='code')),
                ('intitule', models.CharField(max_length=100, verbose_name='intitulé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('duree_etudes', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='durée des études (années)')),
                ('capacite_max', models.PositiveSmallIntegerField(default=50, verbose_name='capacité maximale')),
                ('est_active', models.BooleanField(default=True, verbose_name='est active')),
                ('responsable', models.ForeignKey(blank=True, limit_choices_to={'role': 'RESPONSABLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_dirigees', to=settings.AUTH_USER_MODEL, verbose_name='responsable pédagogique')),
            ],
            options={
                'verbose_name': 'filière',
                'verbose_name_plural': 'filières',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code court de la matière (ex: MATH, PHYS)', max_length=10, unique=True, verbose_name='code')),
                ('intitule', models.CharField(max_length=100, verbose_name='intitulé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('coefficient', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='coefficient')),
                ('est_active', models.BooleanField(default=True, verbose_name='est active')),
                ('enseignant', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_enseignees', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='application.filiere', verbose_name='filière')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='application.niveau', verbose_name='niveau')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['code'],
                'unique_together': {('code', 'filiere', 'niveau')},
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text='Format: ANNEE-CODE-XXXX (ex: 2023-INF-0001)', max_length=20, unique=True, verbose_name='matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='lieu de naissance')),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], max_length=1, verbose_name='genre')),
                ('nationalite', models.CharField(default='Malagasy', max_length=100, verbose_name='nationalité')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide. Ex: +261340000000 ou 0340000000', regex='^\\+?[0-9]{10,15}$')], verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='adresse email')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="date d'inscription")),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('ADMIS', 'Admis'), ('ABANDON', 'Abandon'), ('EXCLU', 'Exclu'), ('DIPLOME', 'Diplômé')], default='INSCRIT', max_length=10, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='application.filiere', verbose_name='filière')),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='application.niveau', verbose_name='niveau')),
            ],
            options={
                'verbose_name': 'étudiant',
                'verbose_name_plural': 'étudiants',
                'ordering': ['nom', 'prenom'],
                'unique_together': {('nom', 'prenom', 'date_naissance')},
            },
        ),
        migrations.CreateModel(
            name='PaiementEcolage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, verbose_name='date de paiement')),
                ('date_echeance', models.DateField(verbose_name="date d'échéance")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=15, verbose_name='statut')),
                ('mois_couvert', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='mois couvert')),
                ('annee_couverte', models.PositiveIntegerField(verbose_name='année couverte')),
                ('mode_paiement', models.CharField(default='Espèces', help_text='Ex: Espèces, Virement, Chèque, etc.', max_length=50, verbose_name='mode de paiement')),
                ('reference', models.CharField(blank=True, help_text='Numéro de référence du paiement', max_length=50, null=True, verbose_name='référence')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_ecolage', to='application.etudiant', verbose_name='étudiant')),
            ],
            options={
                'verbose_name': "paiement d'écolage",
                'verbose_name_plural': "paiements d'écolage",
                'ordering': ['-date_paiement', 'etudiant'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi'), ('SAM', 'Samedi')], max_length=3, verbose_name='jour')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('salle', models.CharField(blank=True, max_length=50, null=True, verbose_name='salle')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('date_debut', models.DateField(verbose_name='date de début de validité')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin de validité')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_donnes', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='application.filiere', verbose_name='filière')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='application.matiere', verbose_name='matière')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='application.niveau', verbose_name='niveau')),
            ],
            options={
                'verbose_name': 'emploi du temps',
                'verbose_name_plural': 'emplois du temps',
                'ordering': ['jour', 'heure_debut'],
                'unique_together': {('filiere', 'niveau', 'jour', 'heure_debut', 'heure_fin')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='note')),
                ('date_evaluation', models.DateField(default=django.utils.timezone.now, verbose_name="date d'évaluation")),
                ('type_evaluation', models.CharField(help_text='Ex: Contrôle continu, Examen final, etc.', max_length=50, verbose_name="type d'évaluation")),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='application.etudiant', verbose_name='étudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='application.matiere', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['-date_evaluation', 'etudiant'],
                'unique_together': {('etudiant', 'matiere', 'type_evaluation')},
            },
        ),
        migrations.CreateModel(
            name='PresenceCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cours', models.DateField(verbose_name='date du cours')),
                ('heure_debut', models.TimeField(verbose_name='heure de début')),
                ('heure_fin', models.TimeField(verbose_name='heure de fin')),
                ('statut', models.CharField(choices=[('P', 'Présent'), ('A', 'Absent'), ('R', 'En retard'), ('E', 'Absence justifiée')], default='P', max_length=1, verbose_name='statut')),
                ('justificatif', models.TextField(blank=True, null=True, verbose_name='justificatif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='application.etudiant', verbose_name='étudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='application.matiere', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'présence au cours',
                'verbose_name_plural': 'présences aux cours',
                'ordering': ['-date_cours', 'heure_debut', 'etudiant'],
                'unique_together': {('etudiant', 'matiere', 'date_cours')},
            },
        ),
    ]
