# Generated by Django 6.0.1 on 2026-01-26 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementecolage',
            name='secretaire',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'SECRETARIAT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='secrétaire'),
        ),
    ]
