# Generated by Django 6.0.1 on 2026-01-26 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_paiementecolage_secretaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='adresse email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('ENSEIGNANT', 'Enseignant'), ('ETUDIANT', 'Étudiant'), ('RESPONSABLE', 'responsable Pédagogique'), ('SECRETARIAT', 'Secrétariat')], default='ENSEIGNANT', max_length=15, verbose_name='rôle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=uuid.uuid4, help_text='Généré automatiquement si non fourni', max_length=150, null=True, unique=True, verbose_name="nom d'utilisateur"),
        ),
    ]
